version: '3.7'
services:
  nestdb:
    image: mongo:5
    restart: always
    container_name: mongo_container
    networks:
      - net_nest
    environment:
      MONGO_DATABASE: nest-pokemon
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  net_nest:
    driver: bridge

volumes:
  mongodb_data_container:
