version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    networks:
      - net_nest
    environment:
      MONGO_INITDB_ROOT_USERNAME: knox
      MONGO_INITDB_ROOT_PASSWORD: knox_pw
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  net_nest:
    driver: bridge

volumes:
  mongodb_data_container:
